### ISSUE TITLE
Strings in single quotes

### ISSUE THREAD

**Issue by ritz078** [DronRathore/javascript-bits#1]
Hi,

I saw you have been using double quotes surrounding the strings but i think using single quotes around the strings has been accepted to be more universal and consistent. 

Let me take an example so that it doesn't look like we should use it just because the world likes it.

When we write a class in the html we generally use double quotes 
```html
<div class="abc"></div>
```
and if we want to write it in a string form (where class is variable) it will create a lot of confusion in case double quotes are used. It seems more consistent with the single quotes as the class still uses the double quotes (as above).

```javascript
var variableClass = 'abc';
var template='<div class=" ' + variableClass + ' "></div>';
```

**Comment by DronRathore** [comment]
@ritz078: Nice thoughts! :blush:
I was also stumbled by the same question when I started adding standard, here is what I think:
- As there is no interpreter based limitation or changes when you use single or double quotes, it turns to be an optional thing.
- You can't use single quotes in a JSON doc, JSON requires double quotes.

So how to deal with an optional thing?
```javascript
var single_var = 'I will have "double" quotes inside me'
var double_var = "I will have a 'single' quote inside me"
var none_var   = "I am free to use any type of quotes"
```

- PHP have a convention of using `'single'`quote for strings, because it interprets them both in different way.
- Its good to have both the cases handled, because when you when you will be having a `'single'` quote within your `'single'` quote, you are going to escape it.
- Provided there is a less tendency of using `'single'` quotes in general(for Browser based JS) we can go with the single quotes, but single quote kind of give me an impression of declaring character constant (*I am sorry but I am from the C language background*)
- For me Javascript is a universal language(front end+back end), so having handled a class addition var for Browser Based JS isn't a use case on the Back end i.e. *NodeJS*
- There are no Perfs difference among both of them, which is good.
- Javascript is a versatile language, so to imply hard standards doesn't seems conventional, unless they really solve a major problem.

This is also a valid code. :wink: 
```javascript
var variableClass = "abc";
var template="<div class=' " + variableClass + " '></div>";
```

However, I will suggest not to use inline templating in your code, I am writing about them all in Perfs section, will update that in this week.

Let me know your thoughts on this. :blush: 

Cheers! :beer:

**Comment by ritz078** [comment]
I understand your viewpoint like how will I write 

```javascript
var a = 'It\'s great to confusion to have'; //doesn't seems so good.
```
but since you are writing a style guide you should be consistent in using them and create a separate section where you mention the other method and their use case.

Their is nothing called the right way here but i think there actually should be a consistent way for the whole project .

How are going to set the .jshintrc when you have used both methods ? I don't think turning off the quotes check is a good idea while linting.

**Comment by DronRathore** [comment]
True! I will add both the cases in the doc. Thanks for that! :blush: 
However, jslint is removing the hard checks of code styles in its next version, specially the quotes one.

You can use `/*jshint -W110 */` directive to ignore the mixed use of both the quotes.

**Comment by ritz078** [comment]
* Add config option for eslint too.

When i get something else, I will surely write here. :smile:

**Comment by DronRathore** [comment]
Awesome! Congrats for being the first contributor to the doc. Will add you to Credits section! :sunglasses: 

Cheers! :beer:

**Comment by ritz078** [comment]
Thanks :smile:
