### ISSUE TITLE
variable names

### ISSUE THREAD

**Issue by ritz078** [DronRathore/javascript-bits#2]
You have used both **underscore** and **camelCase** in variable names. Though camelCase is the preferred method in the js community maybe because 
```javascript
var iLoveJs;
//is smaller than
var i_love_you;
``` 
I would like to know something in favour of camel-case usage .

**Comment by DronRathore** [comment]
Yeah sure.
Camel Case:
- Its not because of the length I must say. JS devs aren't lazy :wink: 
- Class Names, Modules, Global Objects needs to be in camel case, as they implies as a mutable value which is consistent throughout the piece of your code
```javascript
var i_am_a_class = new but_i_look_like_just_another_var() // doesn't make sesnse
var i_am_just_a_var = 42
```
- It helps in differentiating between, Objects and local variables.

Underscore:
- They look dirty - True!
- That's why I prefer naming variables with it, as they remains in a local context and doesn't mess up code readability.

```javascript
some_class_function()
some_local_function()
```
I can't differentiate between the above ones, and has to look around the whole code where this function is written. 

This one looks more promising.
```javascript
var someClassObject = new someClass()
var local_function  = function(){...}
```

Thumb Rule:
- Always camelCase Global variables(even if its global to just a package/module)
- Use underscore for local refs, vars, functions which doesn't need instantiation of class.

**Comment by ritz078** [comment]
I don't see too much in favour of underscore. Why not camelCase everywhere ?

**Comment by DronRathore** [comment]
>Underscore makes easy to differentiate between instance variables and local variables, else there will be no way to differentiate between what is local and what is not.

Using camelCase everywhere will end you up in not able to differentiate between which one is a module/class instance, what is global and what is local and when you will be assigning values or manipulating things, it will be kinda messy for you.

**Comment by ritz078** [comment]
(y) that seems justified .
